### ISSUE TITLE
Coordinate variable time is neither monotonically increasing nor monotonically decreasing on all datasets

### ISSUE THREAD

**Issue by xychen-ocn** [EUREC4A-UK/lagtraj#183] opened 2022-11-16 07:04 UTC
Somehow I seem to attract strange bugs:
I downloaded some data from ERA5 today and encountered the following errors when creating trajectories. It suggests the time variable in this new batch of ERA5 data is weirdly not in ascending order as commonly expected. 
```
Traceback (most recent call last):
  File "/home/xchen/.conda/envs/lagtraj_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xchen/.conda/envs/lagtraj_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xchen/lagtraj/lagtraj/trajectory/create.py", line 445, in <module>
    cli()
  File "/home/xchen/lagtraj/lagtraj/trajectory/create.py", line 407, in cli
    main(data_path=args.data_path, trajectory_name=args.trajectory)
  File "/home/xchen/lagtraj/lagtraj/trajectory/create.py", line 94, in main
    ds_domain = load_domain_data(
  File "/home/xchen/lagtraj/lagtraj/domain/load.py", line 33, in load_data
    ds = era5.load_data(data_path=data_path)
  File "/home/xchen/lagtraj/lagtraj/domain/sources/era5/load.py", line 325, in load_data
    ds = ERA5DataSet(data_path)
  File "/home/xchen/lagtraj/lagtraj/domain/sources/era5/load.py", line 108, in __init__
    self.datasets = datasets or _find_datasets(data_path=data_path)
  File "/home/xchen/lagtraj/lagtraj/domain/sources/era5/load.py", line 59, in _find_datasets
    ds_ = xr.open_mfdataset(files, combine="by_coords")
  File "/home/xchen/.conda/envs/lagtraj_env/lib/python3.8/site-packages/xarray/backends/api.py", line 936, in open_mfdataset
    combined = combine_by_coords(
  File "/home/xchen/.conda/envs/lagtraj_env/lib/python3.8/site-packages/xarray/core/combine.py", line 975, in combine_by_coords
    concatenated = _combine_single_variable_hypercube(
  File "/home/xchen/.conda/envs/lagtraj_env/lib/python3.8/site-packages/xarray/core/combine.py", line 626, in _combine_single_variable_hypercube
    combined_ids, concat_dims = _infer_concat_order_from_coords(list(datasets))
  File "/home/xchen/.conda/envs/lagtraj_env/lib/python3.8/site-packages/xarray/core/combine.py", line 111, in _infer_concat_order_from_coords
    raise ValueError(
ValueError: Coordinate variable time is neither monotonically increasing nor monotonically decreasing on all datasets
```

I then ncdumped the time variable from `an_single_2020-02-14.nc (downloaded today)` and compared it to the time variable in a previous downloaded dataset  `an_single_2020-02-13.nc` (which didn't trigger errors at all). Indeed, the time in `an_single_2020-02-14.nc` is out of order like:

```
array(['2020-02-14T00:00:00.000000000', '2020-02-14T06:00:00.000000000',
       '2020-02-14T12:00:00.000000000', '2020-02-14T18:00:00.000000000',
       '2020-02-14T01:00:00.000000000', '2020-02-14T02:00:00.000000000',
       '2020-02-14T03:00:00.000000000', '2020-02-14T04:00:00.000000000',
       '2020-02-14T05:00:00.000000000', '2020-02-14T07:00:00.000000000',
       '2020-02-14T08:00:00.000000000', '2020-02-14T09:00:00.000000000',
       '2020-02-14T10:00:00.000000000', '2020-02-14T11:00:00.000000000',
       '2020-02-14T13:00:00.000000000', '2020-02-14T14:00:00.000000000',
       '2020-02-14T15:00:00.000000000', '2020-02-14T16:00:00.000000000',
       '2020-02-14T17:00:00.000000000', '2020-02-14T19:00:00.000000000',
       '2020-02-14T20:00:00.000000000', '2020-02-14T21:00:00.000000000',
       '2020-02-14T22:00:00.000000000', '2020-02-14T23:00:00.000000000'],
      dtype='datetime64[ns]')
```

It seems to me that the ERA5 data needs to be sorted by time first before any lagtraj operation to avoid these sort of permutations in the time variable. What do you think??

**Comment by sjboeing** [comment] 2022-11-16 13:26
Thanks @xychen-ocn: it looks like it puts 6-hourly data first (not sure where the 6-hour time scale would come from, maybe it has to do with when forecasts are initialised). Sorting the data upon loading it seems like a sensible strategy. @leifdenby: what do you think?

**Comment by leifdenby** [comment] 2022-11-22 09:27
> Somehow I seem to attract strange bugs:
> I downloaded some data from ERA5 today and encountered the following errors when creating trajectories. It suggests the time variable in this new batch of ERA5 data is weirdly not in ascending order as commonly expected.

Hi @xychen-ocn - thanks for creating this issue! :)

Could you put the exact commands you ran in here so I can try and reproduce the issue? If you're working off a branch could you point me to that too? If I have that I can have a look and try and work out what is going on

**Comment by ralphburton** [comment] 2022-11-25 11:26
Hi @sjboeing @leifdenby @xychen-ocn 

I got the same problem when testing lagtraj on Archer2.

python -m lagtraj.domain.download lagtraj://eurec4a_circle 20200202 20200202

...ok, all files downloaded

python -m lagtraj.trajectory.create lagtraj://eurec4a_20200202_first_short

...gets "ValueError: Coordinate variable time is neither monotonically increasing nor monotonically decreasing on all datasets"

This after using python -m pip install lagtraj on Archer2 (this morning)

The problem seems to be in an_single

E.g. ncdump -v time an_model_2020-02-02.nc
time = 1052664, 1052665, 1052666, 1052667, 1052668, 1052669, 1052670, 
    1052671, 1052672, 1052673, 1052674, 1052675, 1052676, 1052677, 1052678, 
    1052679, 1052680, 1052681, 1052682, 1052683, 1052684, 1052685, 1052686, 
    1052687 ;

...looks OK, but ncdump -v time an_single_2020-02-02.nc
time = 1052664, 1052670, 1052676, 1052682, 1052665, 1052666, 1052667, 
    1052668, 1052669, 1052671, 1052672, 1052673, 1052674, 1052675, 1052677, 
    1052678, 1052679, 1052680, 1052681, 1052683, 1052684, 1052685, 1052686, 
    1052687 ;

...not OK! As @sjboeing says it has put the 6-hourly data first. As far as I can see only the an_single file has this strange time ordering. All others seem OK.

**Comment by ralphburton** [comment] 2022-11-25 14:47
Follow up:

You can replicate the fault with the python script below.

If you use the file as-is, the times are OK.

If you change the date to 2020, you get the error...

Seems like the fault is at their end, is their netcdf still experimental? If I download the 2020 grib file instead, it seems to be in the correct order (I think).

#!/usr/bin/env python
import cdsapi
c = cdsapi.Client()
c.retrieve("reanalysis-era5-complete",
{
"class": "ea",
"expver": "1",
"levtype": "sfc",
"param": (
            "27.128/28.128/29.128/30.128/31.128/32.128/33.128/34.128"
            "/35.128/39.128/40.128/41.128/42.128/66.128/67.128"
            "/129.128/134.128/136.128/139.128/141.128/151.128/159.128"
            "/160.128/161.128/162.128/163.128/164.128/170.128/172.128"
            "/183.128/186.128/187.128/188.128/198.128/235.128/236.128"
            "/238.128/243.128/244.128/245.128"
        ),
"stream": "oper",
"date": "2022-02-02/to/2022-02-02",
"time": "0000/to/2300/by/0100",
"type": "an",
"grid": "1.0/1.0",
"format": "netcdf",
}, "download.netcdf")

**Comment by leifdenby** [comment] 2022-11-25 15:01
> I got the same problem when testing lagtraj on Archer2.

Thanks for this @ralphburton ! I'll have a look this. Thanks for the providing the commands to reproduce.

**Comment by sjboeing** [comment] 2022-11-25 16:00
Thanks @ralphburton: we can either try to fix the order as a part of the download process, or when the files are read into Lagtraj. Not sure what is best.

**Comment by xychen-ocn** [comment] 2022-11-26 18:30
Thanks @ralphburton for sharing your experience and providing the commands too!

@leifdenby My commands are pretty similar except that I downloaded in a self-defined domain and for a series of days using bash script. Below is an example for a particular day. 

```sh
python -m lagtraj.domain.download atomic_northwest_atlantic 2020-02-14 2020-02-15 --retry-rate 60

python -m lagtraj.trajectory.create ATOMIC_RHB_2020-02-14_2020-02-15
```

My yaml input file for creating the domain:`atomic_northwest_atlantic.yaml`
```ml
source    : era5
version   : 1.0.0
lat_min   : 10
lat_max   : 30
lon_min   : -60
lon_max   : -40
lat_samp   : 0.1
lon_samp   : 0.1
```

The trajectory yaml input file: `ATOMIC_RHB_2020-02-14_2020-02-15.yaml`
```ml
trajectory_type : lagrangian
version         : 1.0.0
velocity_method : single_height_level
velocity_method_height : 500              
domain          : atomic_northwest_atlantic               #eurec4a_northwest_atlantic
lat_origin      :  15.00000
lon_origin      :  -53.00000
datetime_origin : "2020-02-14T12:00"
backward_duration : PT12H
forward_duration : PT12H
timestep        : PT1H
```

**Comment by leifdenby** [comment] 2022-12-07 13:32
@ralphburton and @xychen-ocn sorry for delay here. I hope to get a chance to look at this this week. I'll let you know :smile:

**Comment by leifdenby** [comment] 2022-12-16 10:45
@xychen-ocn and @ralphburton I've implemented a fix for this (which @sjboeing tested) that was merged into `master` in #189, and we've just tagged and released v0.1.2 of lagtraj. There are a few other fixes that we've done too (you can see the full changelog here: https://github.com/EUREC4A-UK/lagtraj/releases/tag/v0.1.2). So you should be able to pull the `master` branch into your local copy (or upgrade with pip `pip install --upgrade lagtraj`) to get these fixes.

The fix sorts the loaded data at the time of reading from disk, rather than overwriting the existing files. Hopefully this isn't too slow. If it turns out not to work very well then we'll have to come up with a different fix :)

Hopefully that should fix the issue for you! Let me know if not :smile:

**Comment by ralphburton** [comment] 2022-12-21 11:38
@leifdenby @xychen-ocn I've tried it....it works! Great stuff, thanks Leif. 

Also completed all the commands on the github lagtraj page - all works fine!

I just have one small query and some comments on the read-me that I'll raise as separate issues.

Thanks again for sorting it out - have a great Christmas break all.

Cheers
Ralph

**Comment by sjboeing** [comment] 2023-01-10 12:49
@leifdenby: shall we close this?

**Comment by leifdenby** [comment] 2023-01-12 15:36
yes, I was waiting to see if this resolved the issue for @xychen-ocn too. But yes, let's close and then you can always re-open @xychen-ocn if the problem still persists! :)

**Closed by leifdenby** 2023-01-12 15:36 UTC
